### ISSUE TITLE
設定ファイル（TOML）完全スキーマ仕様書作成

### ISSUE THREAD

**Issue by shun** [shun/ghwt#2]
# 設定ファイル（TOML）完全スキーマ仕様書作成

## 📋 概要
GHWT プロジェクトの設定ファイル `config.toml` の完全スキーマ仕様書を作成し、設定管理の統一基盤を確立する。

## 🎯 目的
- XDG Base Directory Specification準拠の設定ファイル仕様を定義
- 全設定項目のスキーマとバリデーションルールを明確化
- 設定の優先順位（環境変数 > 設定ファイル > デフォルト）を定義

## 📝 作成する成果物
`docs/003-specifications/config-schema.md` ファイルを作成

#### 1. 設定ファイル配置場所
- XDG Base Directory Specification準拠のパス定義
- `$XDG_CONFIG_HOME/ghwt/config.toml` または `~/.config/ghwt/config.toml`

#### 2. 完全なTOMLスキーマ定義
```toml
[core]
root = "~/ghwt"           # string, デフォルト値
auto-prune = false        # boolean, デフォルト値

[git]
default-remote = "origin" # string, デフォルト値
# その他の設定項目...
```

#### 3. 各設定項目の詳細仕様
- **型**: string, boolean, integer, array等
- **デフォルト値**: 設定ファイルが存在しない場合の値
- **バリデーションルール**: 許可される値の範囲・形式
- **説明**: 各設定項目の用途と影響

#### 4. 設定の優先順位
1. 環境変数（`GHWT_*`）
2. 設定ファイル（`config.toml`）
3. デフォルト値

#### 5. 設定管理コマンド仕様
- `ghwt config set <key> <value>`
- `ghwt config get <key>`
- `ghwt config list [--json]`

## 📋 参考資料
- `docs/002-requirements/requirements-ja.md` - 基本要件
- XDG Base Directory Specification
- TOML v1.0.0 仕様

## 📋 依存関係
**前提条件**: 
- CLI インターフェース完全仕様書作成

**ブロック対象**: このIssueが完了すると以下が着手可能
- 内部データ構造仕様書作成
- 管理機能（ls/rm/prune）実装仕様書作成

## ✅ 完了条件
- [ ] `docs/003-specifications/config-schema.md` ファイルが作成されている
- [ ] 完全なTOMLスキーマが定義されている
- [ ] 全設定項目のバリデーションルールが明記されている
- [ ] 設定の優先順位が明確に定義されている
- [ ] 設定管理コマンドの仕様が含まれている

## 🏷️ ラベル
`specification`, `phase-1`, `high-priority`, `config-management`

## 📅 想定工数
1-2時間（仕様書作成）
