### ISSUE TITLE
PBI-INFRA-001 Rust Dev Env Setup

### ISSUE THREAD

**Issue by shun** [shun/ghwt#20]
---
**PBI-INFRA-001: Rust開発環境セットアップとドキュメント化 (改訂版)**

- **説明:** Rust開発環境をセットアップし、プロジェクトの基本的な規約や手順をドキュメント化する。これには、Rustのバージョン管理、Cargoプロジェクトの初期化、フォーマッター (`rustfmt`) とリンター (`clippy`) の導入と設定、そして基本的な開発手順を記載した `README-ja.md` と `CONTRIBUTING-ja.md` の作成が含まれる。
- **受け入れ基準:**
    - Rustのバージョンが選定され、`README-ja.md` にバッジ形式で明記されている。
    - `cargo init --name ghwt` コマンドにより、プロジェクトルートがRustプロジェクトとして初期化されている。
    - `Cargo.toml` に `edition = "2024"` が設定されている。
    - `rustfmt` が導入され、設定ファイル (`rustfmt.toml`) がプロジェクトルートに配置されている。
    - `clippy` が導入され、設定ファイル (`clippy.toml`) がプロジェクトルートに配置されている。
    - `README-ja.md` が作成され、プロジェクトの概要、Rustバージョン、基本的なビルド・実行コマンドが記載されている (内容は要件定義書を考慮)。
    - `CONTRIBUTING-ja.md` が作成され、開発環境のセットアップ手順、コーディングスタイル、リンター・フォーマッターの利用方法、VS Codeの推奨設定 (参考情報として) が記載されている。
    - 標準的な `.gitignore` ファイルが作成され、コミットされている。

**タスクリスト (改訂版):**

- [ ] **タスク1: Rustバージョンの選定とバッジの追加 (`README-ja.md`)**
    - [ ] 1.1. プロジェクトで使用するRustの安定版 (stable) の最新バージョンとして **1.87.0** を選定する。
    - [ ] 1.2. `README-ja.md` ファイルの2行目 (既存のライセンスバッジが記載されている行) の末尾に、Rustバージョンバッジを追記し、複数のバッジが一行に横並びで表示されるようにする。具体的な変更は以下の差分イメージを参照。
        - **対象ファイル:** `README-ja.md`
        - **変更箇所:** 2行目
        - **差分イメージ:**
          ```diff
          - [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
          + [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) [![Rust Version](https://img.shields.io/badge/rust-1.87.0-orange.svg)](https://www.rust-lang.org)
          ```
    - [ ] 1.3. `README-ja.md` をGitにコミットする。
        - コミットメッセージ: `docs: Add Rust version badge to README-ja.md`

- [ ] **タスク2: Cargoプロジェクトの初期化**
    - [ ] 2.1. プロジェクトのルートディレクトリで、以下のコマンドを実行し、既存のディレクトリをRustプロジェクトとして初期化する。
        ```bash
        cargo init --name ghwt
        ```
        - *注意: `cargo new ghwt` ではない。`cargo init` はカレントディレクトリをプロジェクト化する。`--name ghwt` で `Cargo.toml` 内のパッケージ名を `ghwt` に設定する。*
    - [ ] 2.2. 生成された `Cargo.toml` ファイルを開き、`[package]` セクションの `edition` が `"2024"` であることを確認する。もし異なれば `"2024"` に修正する。
        - `Cargo.toml` の確認箇所:
          ```toml
          [package]
          name = "ghwt"
          version = "0.1.0"
          edition = "2024" # ここを確認・修正
          ```
        - *補足: Rust 2024 Edition は現時点での最新Editionです。*
    - [ ] 2.3. リリースビルド時に `dbg!` マクロの使用を禁止するため、`Cargo.toml` ファイルの末尾に以下を追記する。
        ```toml
        [profile.release]
        rustflags = ["-D", "clippy::dbg_macro"]
        ```

- [ ] **タスク3: `rustfmt` (フォーマッター) の導入と設定**
    - [ ] 3.1. `rustfmt` がインストールされていない場合は、以下のコマンドでインストールする。
        ```bash
        rustup component add rustfmt
        ```
    - [ ] 3.2. プロジェクトルートに `rustfmt.toml` ファイルを作成し、以下の内容を記述する。
        ```toml
        # rustfmt.toml
        # Use defaults for most things
        version = "Two" # Specifies the version of rustfmt rules to use. "Two" is the latest.
        max_width = 100 # Maximum line width
        use_small_heuristics = "Max" # More aggressively formats lines to fit within max_width
        reorder_imports = true # Reorder import statements alphabetically
        reorder_modules = true # Reorder module statements alphabetically
        remove_nested_parens = true # Remove nested parentheses where possible
        short_array_element_width_threshold = 10 # Threshold for deciding to put array elements on new lines
        struct_lit_width = 60 # Width threshold for struct literals before breaking to multiple lines
        fn_call_width = 60 # Width threshold for function calls before breaking to multiple lines
        # For more options: https://rust-lang.github.io/rustfmt/
        ```

- [ ] **タスク4: `clippy` (リンター) の導入と設定**
    - [ ] 4.1. `clippy` がインストールされていない場合は、以下のコマンドでインストールする。
        ```bash
        rustup component add clippy
        ```
    - [ ] 4.2. プロジェクトルートに `clippy.toml` ファイルを作成し、以下の内容を記述する。
        ```toml
        # clippy.toml

        # correctness: ほぼ常にバグである可能性が高いものを指摘
        # deny = ["clippy::correctness"] # デフォルトで deny のものが多いので、個別指定でも良い

        # suspicious: バグの可能性がある、または紛らわしいコードを指摘
        deny = ["clippy::suspicious"]

        # style: コードスタイルに関する指摘
        deny = ["clippy::style"]

        # complexity: 不必要に複雑なコードを指摘
        deny = ["clippy::complexity"]

        # perf: パフォーマンスに影響を与える可能性のあるコードを指摘
        deny = ["clippy::perf"]

        # pedantic: 非常に細かい、あるいは好みが分かれる可能性のある規約的な指摘
        # プロジェクト開始時は warn にしておき、徐々に deny に移行するか、
        # 個別に allow するリントを増やす運用も考えられます。
        deny = ["clippy::pedantic"]

        # restriction: 特定の機能の使用を制限する
        deny = ["clippy::restriction"]

        # cargo: Cargo.toml の内容に関する指摘
        deny = ["clippy::cargo"]

        # nursery: 新しい、実験的なリント
        deny = ["clippy::nursery"]

        # ---- 個別のリント設定例 (上記グループ設定と合わせて調整) ----

        # ドキュメント関連の警告をエラーに
        deny = ["missing_docs"] # rustc のリント
        # deny = ["clippy::missing_errors_doc"] # pedantic グループに含まれるため不要な場合あり
        # deny = ["clippy::missing_panics_doc"] # pedantic グループに含まれるため不要な場合あり

        # allow するリントの例 (必要に応じてコメントアウトを解除)
        # allow = ["clippy::module_name_repetitions"]
        # allow = ["clippy::struct_excessive_bools"]
        # allow = ["clippy::too_many_lines"]
        # allow = ["clippy::cognitive_complexity"]

        # For a list of all lints and their details:
        # https://rust-lang.github.io/rust-clippy/master/
        ```
    - [ ] `clippy.toml` をGitにコミットする。
    - [ ] ターミナルで `cargo clippy -- -D warnings` コマンドを実行し、`allow` した以外の `clippy::pedantic` からの警告や、その他のエラーが出ないことを確認する。

- [ ] **`CONTRIBUTING-ja.md` の作成と編集**
    - [ ] プロジェクトのルートディレクトリ (`ghwt` ディレクトリ直下) に `CONTRIBUTING-ja.md` ファイルを作成する。
    - [ ] `CONTRIBUTING-ja.md` に以下の内容をコピー＆ペーストして保存する。
        ```markdown
        # コントリビューションガイド

        このドキュメントは、GHWTプロジェクトへの貢献方法について説明します。

        ## 開発環境のセットアップ

        1.  Rustのインストール: [README-ja.md](./README-ja.md) の指示に従ってください。
        2.  `rustfmt` (フォーマッター) のインストール: `rustup component add rustfmt`
        3.  `clippy` (リンター) のインストール: `rustup component add clippy`

        ## コーディングスタイル

        コードのフォーマットには `rustfmt` を使用します。設定はプロジェクトルートの `rustfmt.toml` に定義されています。
        コミット前に `cargo fmt` を実行してください。

        コードの静的解析には `clippy` を使用します。設定はプロジェクトルートの `clippy.toml` に定義されています。
        コミット前に `cargo clippy -- -D warnings` を実行し、エラーや警告がないことを確認してください。

        ## (参考) VS Code での推奨設定

        VS Code と `rust-analyzer` 拡張機能を使用する場合、以下の設定をプロジェクトの `.vscode/settings.json` (Git管理外) に記述すると、保存時に自動でフォーマットが実行されるようになります。

        ```json
        // .vscode/settings.json (このファイルは .gitignore に追加することを推奨します)
        {
            "editor.formatOnSave": true,
            "[rust]": {
                "editor.defaultFormatter": "rust-lang.rust-analyzer",
                "editor.tabSize": 4,
                "editor.insertSpaces": true
            },
            "files.eol": "\n" // 改行コードをLFに統一
        }
        ```

        ## プルリクエストのプロセス

        TODO: プルリクエストの作成手順、レビュープロセスなどを記述する

        ## Issueの報告

        TODO: Issueの報告テンプレートやガイドラインを記述する
        ```
    - [ ] `CONTRIBUTING-ja.md` をGitにコミットする。
- [ ] **`.gitignore` の作成と編集**
    - [ ] プロジェクトのルートディレクトリ (`ghwt` ディレクトリ直下) に `.gitignore` ファイルを作成する。
    - [ ] `.gitignore` に以下の内容をコピー＆ペーストして保存する。
        ```gitignore
        # Rust
        /target/
        Cargo.lock

        # IDEs
        .idea/
        .vscode/ # settings.json など個人設定を含むため、共有しない場合はignore
        *.iml
        *.ipr
        *.iws

        # OS generated files
        .DS_Store
        .DS_Store?
        ._*
        .Spotlight-V100
        .Trashes
        ehthumbs.db
        Thumbs.db
        ```
    - [ ] `.gitignore` をGitにコミットする。

---
