### ISSUE TITLE
PBI-INFRA-002: 基本的なCIパイプラインの構築

### ISSUE THREAD

**Issue by shun** [shun/ghwt#21]
---
**PBI-INFRA-002: 基本的なCIパイプラインの構築**

- **説明:** プロジェクトの品質を維持し、自動化されたチェックを行うために、GitHub Actions を利用した基本的なCI（継続的インテグレーション）パイプラインを構築する。このパイプラインには、コードのフォーマットチェック、リンターチェック、ビルド、テストの実行が含まれる。
- **受け入れ基準:**
    - GitHub Actions のワークフローファイルが `.github/workflows` ディレクトリに作成されている。
    - masterブランチへのpush時、およびpull_request作成・更新時にワークフローがトリガーされる。
    - ワークフロー内で以下のジョブが順次実行され、すべて成功する。
        - リポジトリのコードのチェックアウト
        - 指定されたRustバージョンのセットアップ
        - Cargo依存関係のキャッシュ
        - `cargo fmt --check` (フォーマットチェック)
        - `cargo clippy -- -D warnings` (リンターチェック)
        - `cargo build` (ビルド)
        - `cargo test` (テスト実行)
    - `README-ja.md` にCIステータスを示すバッジが追加されている。

**タスクリスト:**

- [ ] **タスク1: GitHub Actions ワークフローファイルの作成**
    - [ ] 1.1. プロジェクトルートに `.github/workflows` ディレクトリを作成する。
        ```bash
        mkdir -p .github/workflows
        ```
    - [ ] 1.2. `.github/workflows` ディレクトリ内に `rust.yml` という名前で新しいファイルを作成する。
    - [ ] 1.3. `rust.yml` に以下の内容を記述する。
        ```yaml
        name: Rust CI

        on:
          push:
            branches: [ main ] # mainブランチへのpushで実行
          pull_request:
            branches: [ main ] # mainブランチへのpull_requestで実行

        env:
          CARGO_TERM_COLOR: always
          RUST_VERSION: 1.87.0 # PBI-INFRA-001で選定したバージョン

        jobs:
          build_and_test:
            name: Build and Test
            runs-on: ubuntu-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v4

              - name: Setup Rust toolchain
                uses: dtolnay/rust-toolchain@stable
                with:
                  toolchain: ${{ env.RUST_VERSION }}
                  components: rustfmt, clippy

              - name: Cache Cargo dependencies
                uses: actions/cache@v4
                with:
                  path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

              - name: Check formatting
                run: cargo fmt --check

              - name: Run linter (Clippy)
                run: cargo clippy -- -D warnings

              - name: Build project
                run: cargo build --verbose

              - name: Run tests
                run: cargo test --verbose
        ```
    - [ ] 1.4. `.github/workflows/rust.yml` をGitにコミットする。
        - コミットメッセージ: `ci: Add basic Rust CI workflow for GitHub Actions`

- [ ] **タスク2: CIステータスバッジの追加 (`README-ja.md`)**
    - [ ] 2.1. `README-ja.md` ファイルの2行目 (既存のバッジが記載されている行) の末尾に、CIステータスバッジを追記し、複数のバッジが一行に横並びで表示されるようにする。具体的な変更は以下の差分イメージを参照。
        - **対象ファイル:** `README-ja.md`
        - **変更箇所:** 2行目
        - **差分イメージ (仮のバッジURL、実際のURLはワークフロー作成後にGitHubから取得):**
          ```diff
          - [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) [![Rust Version](https://img.shields.io/badge/rust-1.87.0-orange.svg)](https://www.rust-lang.org)
          + [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) [![Rust Version](https://img.shields.io/badge/rust-1.87.0-orange.svg)](https://www.rust-lang.org) [![Rust CI](https://github.com/shun/ghwt/actions/workflows/rust.yml/badge.svg)](https://github.com/shun/ghwt/actions/workflows/rust.yml)
          ```
        - *注意: 上記のCIバッジURL (`https://github.com/shun/ghwt/...`) は、実際のユーザー名/リポジトリ名に置き換えてください。また、ワークフローファイル名 (`rust.yml`) が異なる場合は、それに応じて修正してください。GitHub Actionsのワークフローページから正しいバッジのMarkdownスニペットを取得できます。*
    - [ ] 2.2. `README-ja.md` をGitにコミットする。
        - コミットメッセージ: `docs: Add CI status badge to README-ja.md`

- [ ] **タスク3: 動作確認**
    - [ ] 3.1. 変更をリモートリポジトリのmainブランチにpushする (またはmainブランチへのPull Requestを作成してマージする)。
    - [ ] 3.2. GitHubリポジトリの「Actions」タブを開き、CIワークフローが正常に実行され、すべてのステップが成功することを確認する。
    - [ ] 3.3. `README-ja.md` に表示されているCIバッジが、現在のCIステータス (例: passing) を正しく反映していることを確認する。

---
